"""Sweep the guard's thresholds against retrieved contexts recorded during the matrix run.

The shipped operating point was chosen deliberately rather than tuned to flatter the
result. That choice needs a curve behind it: what does moving each threshold cost, in
missed revoked facts versus withheld current ones?

This replays the guard over retrieved contexts captured by re-running the retrieval
probes (`retrieval_contexts.json`). No model calls and no live backends are involved: the
contexts are fixed, so the only thing varying across rows is the guard's own parameters.

Ground truth is the store's own verdict: a fact present in default retrieval but absent
once that system's status filter is applied was classified revoked by the system itself.
Contexts where filtering removed nothing therefore offer no true positive to find, and
can only accrue false positives, which is the honest way to count them.

Run:  uv run python tools/guard_sweep.py           # engineer-facing GUARD_SWEEP.md
      uv run python tools/guard_sweep.py --paper   # also writes GUARD_SWEEP_PAPER.md: the
                                                       # same table with prose system labels
                                                       # and no generator boilerplate
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / 'core'))
sys.path.insert(0, str(ROOT / 'guard'))

from dotenv import load_dotenv  # noqa: E402

load_dotenv(ROOT / '.env')

from stale_guard import GuardConfig, guard  # noqa: E402

PAPER = '--paper' in sys.argv


def system_label(system: str, paper: bool) -> str:
    """`graphiti[show_expired]/natural` -> `graphiti (show_expired), natural seeding` for
    the reader-facing report; the bracket/slash shorthand is an internal (project,
    variant, mode) tuple encoding, not something a reader should have to decode."""
    if not paper:
        return system
    proj_variant, _, mode = system.partition('/')
    proj, _, variant = proj_variant.partition('[')
    variant = variant.rstrip(']')
    name = f'{proj} ({variant})' if variant and variant != 'default' else proj
    seeding = 'controlled' if mode == 'direct' else 'natural'
    return f'{name}, {seeding} seeding'


def _dir(var: str, default: Path) -> Path:
    v = os.getenv(var)
    if not v:
        return default
    return Path(v) if os.path.isabs(v) else (ROOT / v).resolve()


RES = _dir('RESULTS_DIR', ROOT.parent / 'private' / 'results')
REPORTS = _dir('REPORTS_DIR', ROOT.parent / 'private' / 'reports')


def load_contexts() -> list[dict]:
    """Retrieved contexts with the store's own revoked/current labels.

    Read from `retrieval_contexts.json`, produced by re-running the retrieval probes.
    The matrix stores per-context counts but not the records themselves, and the sweep
    needs the records; retrieval is the cheap stage, so recovering them costs far less
    than repeating the full run.
    """
    path = RES / 'retrieval_contexts.json'
    if not path.exists():
        sys.exit(f'{path} not found; re-run the retrieval probes to capture contexts')
    out = []
    for c in json.loads(path.read_text()):
        # Ground truth from the store itself: present by default, absent once the status
        # filter is applied => that system classified it revoked.
        defense = set(c['defense_facts'])
        revoked = [f for f in c['attack_facts'] if f not in defense]
        out.append({'system': c['system'], 'records': c['attack_records'],
                    'revoked': set(revoked)})
    return out


def score(contexts: list[dict], cfg: GuardConfig) -> dict:
    """Per-fact scoring against the store's own labels."""
    tp = fn = fp = kept = 0
    for c in contexts:
        res = guard(c['records'], cfg)
        withheld = {w['text'] for w in res.withheld}
        revoked = c['revoked']
        tp += len(withheld & revoked)
        fn += len(revoked - withheld)
        fp += len(withheld - revoked)
        kept += len(res.kept)
    return {'true_positives': tp, 'false_negatives': fn,
            'false_positives': fp, 'kept': kept}


def build_report(contexts: list[dict], rows: list, paper: bool) -> list[str]:
    out = ['# Guard threshold sweep', '']
    if not paper:
        out += ['_Generated by tools/guard_sweep.py. Do not edit by hand._', '']
    out += [
        f'Replayed over {len(contexts)} retrieved contexts captured from the same probes '
        'used in the main evaluation. No model calls or live backends are involved, so '
        'the only thing varying across rows is the guard\'s own configuration.',
        '',
        'Ground truth is the store\'s own verdict: a fact present in default retrieval but '
        'absent once the status filter is applied was classified revoked by the system '
        'itself. Contexts where filtering removed nothing contribute no true positives, '
        'there was nothing to find, so they can only accrue false positives, which is the '
        'honest way to count them.',
        '',
        '| parameter | value | caught (TP) | missed (FN) | current facts withheld (FP) | facts kept |',
        '|---|---|---|---|---|---|',
    ]
    for name, v, is_default, sc in rows:
        mark = ' **(shipped)**' if is_default else ''
        out.append(f"| {name} | {v}{mark} | {sc['true_positives']} | {sc['false_negatives']} "
                   f"| {sc['false_positives']} | {sc['kept']} |")

    # Per-system breakdown: the aggregate is dominated by stores that mark nothing, so
    # reporting only the total would misattribute their false positives to the guard's
    # tuning rather than to the absence of anything to key on.
    base = GuardConfig()
    out += ['', '## Where the errors come from', '',
            'The aggregate above is misleading on its own. Stores that never record a '
            'revocation mark offer no true positive to find, so every withholding there '
            'counts as a false positive regardless of threshold. Broken out:', '',
            '| system | caught | missed | withheld in error |', '|---|---|---|---|']
    per = {}
    for c in contexts:
        res = guard(c['records'], base)
        w = {x['text'] for x in res.withheld}
        a = per.setdefault(c['system'], [0, 0, 0])
        a[0] += len(w & c['revoked'])
        a[1] += len(c['revoked'] - w)
        a[2] += len(w - c['revoked'])
    for k in sorted(per):
        tp, fn, fp = per[k]
        note = ': store marks nothing; no true positive available' if tp == 0 and fp else ''
        out.append(f'| {system_label(k, paper)} | {tp} | {fn} | {fp}{note} |')

    out += [
        '',
        '## How to read this',
        '',
        'Raising the subject-overlap threshold makes the guard more conservative: fewer '
        'false positives, more missed stale facts. Lowering it does the reverse. Disabling '
        'the opposition requirement withholds on subject match alone and is included to '
        'show why it is not the default. No setting inverts the error ratio: on this '
        'corpus the guard withholds more current facts than revoked ones at every '
        'operating point, because most of the corpus comes from stores with nothing to '
        'key on.',
        '',
        'The shipped operating point is chosen for deployment posture, not for the best '
        'number in this table.',
        '',
        '## What this sweep cannot be compared against',
        '',
        '**These counts are not comparable to the main evaluation.** The contexts here '
        'were captured by re-running the retrieval probes, and several systems are '
        'nondeterministic across runs (fresh vector stores, LLM-driven consolidation '
        'decisions), so their revoked/current labelling differs from the run that '
        'produced the headline numbers. Use this table for the *shape* of the '
        'threshold trade-off only. The guard\'s effectiveness on the main corpus is '
        'reported in the matrix output, where guard scoring and the decision arms share '
        'one set of retrieved contexts.',
    ]
    return out


def main() -> None:
    contexts = load_contexts()
    if not contexts:
        sys.exit('retrieval_contexts.json is empty; re-run the retrieval probes')

    base = GuardConfig()
    rows = []
    for name, values, field in [
        ('subject overlap (alpha)', [0.30, 0.40, 0.45, 0.55, 0.65], 'subject_overlap'),
        ('max withheld fraction (beta)', [0.2, 0.4, 0.6, 0.8, 1.0], 'max_withheld_ratio'),
    ]:
        for v in values:
            cfg = GuardConfig(**{**base.__dict__, field: v})
            rows.append((name, v, v == getattr(base, field), score(contexts, cfg)))
    # require_opposition is a boolean, not a sweep
    for v in (True, False):
        cfg = GuardConfig(**{**base.__dict__, 'require_opposition': v})
        rows.append(('require opposition', v, v == base.require_opposition,
                     score(contexts, cfg)))

    REPORTS.mkdir(parents=True, exist_ok=True)

    out = build_report(contexts, rows, paper=False)
    (REPORTS / 'GUARD_SWEEP.md').write_text('\n'.join(out) + '\n')
    print('\n'.join(out))

    if PAPER:
        sys.path.insert(0, str(ROOT / 'core'))
        from sanitize import public_text
        paper_out = build_report(contexts, rows, paper=True)
        paper_text = public_text('\n'.join(paper_out) + '\n')
        (REPORTS / 'GUARD_SWEEP_PAPER.md').write_text(paper_text)
        print(f'\nwrote {REPORTS / "GUARD_SWEEP_PAPER.md"} (reader-facing, sanitised)')


if __name__ == '__main__':
    main()
